### ISSUE TITLE
Way to avoid Video Converter download?

### ISSUE THREAD

**Issue by sebadelcampo1** [neurospeech/xamarin-android-ffmpeg#10]
Hey, thank you a lot for this! It's working great.

Sorry if this isn't really an issue, but I was wondering if there's any way to pre-install the Video Converter with the app so as to avoid users having to download it first time they want to edit a video.

I have been trying for the past days without success, thought that if it's possible maybe you can point me in the right direction.

Thank you

**Comment by neurospeech** [comment]
FFMpeg is roughly 10 mb in size, multiply it by different CPU model, ARM + x86 + ARMv7, all of them combined works out to be 30mb. Everytime you release new version, you have to ship same content of roughly 30 mb size. That's why, once downloaded, the file stays in your app's directory even when you ship new version, this reduces the number of bytes you need to download.

Also, you can implement your own CDN and change the location of file to download from.

You can include ffmpeg as resource in your project, and you can follow procedure of copying it on local folder and making it an executable.

**Comment by neurospeech** [comment]
For Android 6.0 and after, please use MP4Transcoder as mentioned in README.md. This will not download anything and it will only use native android transcoder.
